name: Build and Publish on Merge
on:
  push:
    branches:
      - "dev"

env:
  IMAGE_NAME: ${{vars.AUTHEN_SERVICE_REPO}}
  APP_NAME: Authen Service
  FILE_PATH: config/system/4-authen-service-deployment.yaml
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
    
      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{env.IMAGE_NAME}}:latest

      - name: Build Success
        uses : rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: |
            Build **${{env.APP_NAME}}** success!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    
      - name: Build Fail
        uses : rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: |
            Build **${{env.APP_NAME}}** failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    
    outputs:
      version: ${{steps.build.outputs.digest}}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Infra Config Repo
        uses: actions/checkout@v3
        with:
          repository: FUnigrad/funiverse-infra-config
          token: ${{secrets.PUSH_GITHUB_TOKEN}}
          ref: dev
      - name: Get Version
        run: echo "VERSION=${{needs.build-and-push.outputs.version}}" >> $GITHUB_ENV
      - name: Update Manifest
        run: |
          sed -i "s+${{env.IMAGE_NAME}}.*+${{env.IMAGE_NAME}}@${{env.VERSION}}+g" ${{env.FILE_PATH}}
      - name: Commit and push
        run: |
          git config --global user.name 'nqbao11'
          git config --global user.email 'nqbao11.01@gmail.com'
          git commit -am "Deployed latest ${{env.IMAGE_NAME}} by https://github.com/${{github.repository}}/commit/${{github.event.pull_request.head.sha}}"
          git push

      - name: Deploy Failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: |
            Deploy **${{env.APP_NAME}}** Failed!
            Check log in github action
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deploy Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: |
            Deploy **${{env.APP_NAME}}** Success!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}