name: Dockerize Application
on:
  push:
    branches:
    - devops
  pull_request:
    branches:
    - dev
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Buildx 
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{vars.AUTHEN_SERVICE_REPO}}:v${{github.run_id}}
            ${{vars.AUTHEN_SERVICE_REPO}}:latest
      - name: Build Success
        uses : rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: |
            Build Succeeded!
            Push to hub with following tag: ${{vars.AUTHEN_SERVICE_REPO}}:v${{github.run_id}} and ${{vars.AUTHEN_SERVICE_REPO}}:latest
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build Failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}