name: Build and test on Pull request

on: pull_request
env:
  IMAGE_NAME: ${{vars.AUTHEN_SERVICE_REPO}}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode clean package

      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v2
      #   if: success()
      #   with:
      #     files: |
      #       **/target/surefire-reports/**.xml
    
      - name: Build Success
        uses : rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: |
            - **Commit** : https://github.com/${{ github.repository }}/ commit/${{  github.event.pull_request.head.sha }}
            Build Authen Service succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
      - name: Build Failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: |
            - **Commit** : https://github.com/${{ github.repository }}/commit/${{  github.event.pull_request.head.sha }}
            Build Authen Service failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

